# Generated by Django 4.2.7 on 2023-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_worker_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker', 'verbose_name_plural': 'Workers'},
        ),
        migrations.AddField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('asap', 'ASAP (As Soon As Possible)'), ('medium', 'Medium'), ('critical', 'Critical')], default='medium', max_length=30),
        ),
    ]
